version: '3.8'

services:
  # Backend API Service
  employee-api:
    build:
      context: ./Backend/EmployeeManagement.API
      dockerfile: Dockerfile
    ports:
      - "7000:80"
      - "7001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    networks:
      - employee-network
    restart: unless-stopped

  # Frontend Service
  employee-frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - employee-api
    networks:
      - employee-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - employee-api
      - employee-frontend
    networks:
      - employee-network
    restart: unless-stopped

networks:
  employee-network:
    driver: bridge